/*
 * Initialize jquery components
 * These are all js files from the shopware responsive theme
 */
// shopware legacy
require('jquery');
require('Responsive/jquery.plugin-base.js');
require('Responsive/jquery.state-manager.js');
require('Responsive/jquery.storage-manager.js');
require('Responsive/jquery.off-canvas-menu.js');
require('Responsive/jquery.search.js');
require('Responsive/jquery.tab-menu.js');
require('Responsive/jquery.image-slider.js');
require('Responsive/jquery.image-zoom.js');
require('Responsive/jquery.collapse-panel.js');
require('Responsive/jquery.auto-submit.js');
require('Responsive/jquery.scroll.js');
require('Responsive/jquery.product-slider.js');
require('Responsive/jquery.register.js');
require('Responsive/jquery.modal.js');
require('Responsive/jquery.selectbox-replacement.js');
require('Responsive/jquery.captcha.js');
require('Responsive/jquery.drop-down-menu.js');
require('Responsive/jquery.loading-indicator.js');
require('Responsive/jquery.overlay.js');
require('Responsive/jquery.form-polyfill.js');
require('Responsive/jquery.pseudo-text.js');
require('Responsive/jquery.last-seen-products.js');
require('Responsive/jquery.lightbox.js');
require('Responsive/jquery.ajax-product-navigation.js');
require('Responsive/jquery.newsletter.js');
require('Responsive/jquery.menu-scroller.js');
require('Responsive/jquery.shipping-payment.js');
require('Responsive/jquery.add-article.js');
require('Responsive/jquery.range-slider.js');
require('Responsive/jquery.filter-component.js');
require('Responsive/jquery.listing-actions.js');
require('Responsive/jquery.collapse-cart.js');
require('Responsive/jquery.emotion.js');
require('Responsive/jquery.product-compare-add.js');
require('Responsive/jquery.product-compare-menu.js');
require('Responsive/jquery.infinite-scrolling.js');
require('Responsive/jquery.off-canvas-button.js');
require('Responsive/jquery.subcategory-nav.js');
require('Responsive/jquery.ajax-wishlist.js');
require('Responsive/jquery.preloader-button.js');
require('Responsive/jquery.image-gallery.js');
require('Responsive/jquery.offcanvas-html-panel.js');
require('Responsive/jquery.jump-to-tab.js');
require('Responsive/jquery.ajax-variant.js');
require('Responsive/jquery.csrf-protection.js');
require('Responsive/jquery.panel-auto-resizer.js');
require('Responsive/jquery.address-selection.js');
require('Responsive/jquery.address-editor.js');
require('Responsive/jquery.datepicker.js');
require('Responsive/jquery.storage-field.js');
require('Responsive/jquery.cookie-permission.js');
require('Responsive/jquery.shopware-responsive.js');
